# Generated by Django 2.1.5 on 2019-01-20 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('careers', '0002_activity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='image',
            name='dynamic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='careers.Activity', verbose_name='动态'),
        ),
    ]
