# Generated by Django 2.1.5 on 2019-01-20 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_auto_20190120_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamicgroupref',
            old_name='dynamic',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='dynamic',
            new_name='activity',
        ),
    ]
