# Generated by Django 2.1.5 on 2019-01-20 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_auto_20190120_2059'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useractivityref',
            table='user_activity_ref',
        ),
    ]
