# Generated by Django 2.1.5 on 2019-01-20 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.storage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('careers', '0006_auto_20190120_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='内容')),
                ('superior', models.IntegerField(default=0, verbose_name='上级id')),
                ('data_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.Activity', verbose_name='活动')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(default=None, storage=utils.storage.ImageStorage(), upload_to='group/%Y/%m', verbose_name='图片'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=utils.storage.ImageStorage(), upload_to='activity/%Y/%m', verbose_name='图片'),
        ),
    ]
